### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by 333csx** [Shachar/drinstaller#1]
Thanks for your work !
I had some Issues installing DR:
Please see this post:
https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=206765#p1075142

**Comment by Shachar** [comment]
Please open bug reports with an actual report of the bug if you want it tracked and handled. Thank you.

**Comment by Shachar** [comment]
I did add some comments on the forum, but they will need to be approved by a moderator before they go live.
